#spring.config.activate.on-profile: db-mysql

spring:
  datasource:
    driver-class-name: ${db.driver:com.mysql.cj.jdbc.Driver}
    url: ${db.log4jdbc}jdbc:mysql://${db.host}:3306/${db.schema}?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
  flyway:
    driver-class-name: ${db.driver:com.mysql.cj.jdbc.Driver}
    url: ${db.log4jdbc}jdbc:mysql://${db.host}:3306?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    user: ${db.username}
    password: ${db.password}
    schemas: ${db.schema}
    create-schemas: true
    default-schema: ${db.schema}
