spring:
  data:
    web:
      pageable:
        max-page-size: 2000
  jpa:
    # WARN 78842 --- [main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
    open-in-view: false
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso
#  jackson:
#    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
#    time-zone: Asia/Shanghai
#    locale: zh_CN
#所有应用共用的账号
  security:
    user:
      name: ${MICROSERVICE_SECURITY_USERNAME:peacetrue}
      password: ${MICROSERVICE_SECURITY_PASSWORD:password}
  cloud:
    zookeeper:
      # docker 内运行，需要使用主机名称，主机需要和 docker 配置一致
      connect-string: ${REGISTRY_HOST:localhost:2182}

#授权服务配置（spring-security-oauth2 过期不完善的）
authorization-server:
  hostname: localhost
  port: 8510
  issuerUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}
  jwkSetUri: ${authorization-server.issuerUri}/.well-known/jwks.json


# 禁用此项，以启用 ReactorLoadBalancerExchangeFilterFunction
spring.cloud.loadbalancer.ribbon.enabled: false
# 默认禁用 zipkin
#spring.zipkin.enabled: false

#logging.level.root: DEBUG
#在项目内运行 java 的相对路径
#logging.config: file:peacetrue-microservice-common/logback-spring.xml

#spring.profiles.include: uaa,rabbitmq


---
#生产环境
spring.config.activate.on-profile: prod
#spring.profiles.include: https,fileLog,rabbitmqLog,cmd,zipkin

eureka.instance.hostname: peacetrue.cn
authorization-server.hostname: peacetrue.cn
spring.rabbitmq.host: peacetrue.cn
spring.zipkin.base-url: http://peacetrue.cn:9411

---
#默认 http 协议，激活此配置切换到 https 协议
spring.config.activate.on-profile: https

MICROSERVICE_PROTOCOL: https

server:
  ssl:
    #服务端
    key-store: file://${user.home}/peacetrue.cn.jks
    key-alias: peacetrue.cn
    key-store-password: ${MICROSERVICE_SSL_PASSWORD:password}

#uaa https tomcat 默认 8443
authorization-server.port: 8443
eureka.instance.securePortEnabled: true

---
#zipkin，默认禁用，激活此项以启用
spring.config.activate.on-profile: zipkin
spring.zipkin.enabled: true

---
#命令行
spring.config.activate.on-profile: cmd

# 通过命令行启动会在模块内运行
#logging.config: file:../peacetrue-microservice-common/logback-spring.xml

---
#资源服务配置
spring.config.activate.on-profile: resourceserver

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: ${authorization-server.issuerUri}
          jwkSetUri: ${authorization-server.jwkSetUri}

---
#认证客户端配置
spring.config.activate.on-profile: authorizationclient

spring:
  security:
    oauth2:
      client:
        provider:
          peacetrue:
            issuerUri: ${authorization-server.issuerUri}
            jwkSetUri: ${authorization-server.jwkSetUri}
        registration:
          peacetrue:
            provider: peacetrue
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'

---
#授权服务配置（UAA 完善的），默认使用 spring-security-oauth2，激活此配置使用 UAA
spring.config.activate.on-profile: uaa

authorization-server:
  port: 8080
  issuerUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}/uaa/oauth/token
  jwkSetUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}/uaa/token_keys

---
#消息总线通过 rabbitmq 发送消息
spring.config.activate.on-profile: rabbitmq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

---
# 禁用安全配置
spring.config.activate.on-profile: disable_security

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

