#spring.config.activate.on-profile: log-file

logging:
  level:
    root: warn
# IEDA 中，java 命令执行在项目（不是模块）下
# path 和 file 冲突，设置 file 则 path 无效
#logging.path = backend
# 相对路径基于 java 命令执行时所在的目录
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-history: 30

#server:
#  tomcat:
#    accesslog:
#      enabled: true
#    basedir: tomcat
