server.port: 80

spring:
  cloud:
    gateway:
      routes:
        #配置中心监听
        - id: config_center_monitor
          #配置中心地址
          uri: ${MICROSERVICE_PROTOCOL:http}://${MICROSERVICE_CONFIG_HOST:localhost}:${MICROSERVICE_CONFIG_PORT:8888}/monitor
          predicates:
            - Path=/monitor
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/message/**

        #biog
        - id: biog_front
          uri: http://localhost:3000/
          predicates:
            - Path=/,/*.js,/*.json,/static/**,/_next/**,/room/**,/play/**
        - id: biog_back
          uri: http://localhost:8001/
          predicates:
            - Path=/games/**,/socket.io/**

peacetrue:
  static-resources:
    '[/summarize/**]': file:/root/peacetrue/document-antora/public/
    '[/download/**]': file:/root/peacetrue/download/
    '[/talent_admin/**]': file:/root/peacetrue/peacetrue-talent-page/peacetrue-talent-admin-page/build/
    '[/talent_member/**]': file:/root/peacetrue/peacetrue-talent-page/peacetrue-talent-member-page/public/
    '[/MP_verify_t4rKSxor2Mowtjo?.txt]': file:/usr/share/nginx/html/MP_verify_t4rKSxor2MowtjoC.txt

---
spring.profiles: https

server.port: 443

---
spring.profiles: prod

#logging.level.org.springframework: trace
logging.level.com.github.peacetrue: trace
