server.port: 80

spring:
  cloud:
    gateway:
      routes:
        #配置中心监听
        - id: config_center_monitor
          #配置中心地址
          uri: ${MICROSERVICE_PROTOCOL:http}://${MICROSERVICE_CONFIG_HOST:localhost}:${MICROSERVICE_CONFIG_PORT:8888}/monitor
          predicates:
            - Path=/monitor
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/message/**

        #子域名接口地址处理
        - id: talent-admin-api-session
          uri: http://101.200.133.86:8100
          predicates:
            - Host=talent-admin.peacetrue.cn
            - Path=/api/**
            - Cookie=SESSION,.+
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - RemoveResponseHeader=Set-Cookie
        - id: talent-admin-api
          uri: http://101.200.133.86:8100
          predicates:
            - Host=talent-admin.peacetrue.cn
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: talent-member-api
          uri: http://101.200.133.86:8110
          predicates:
            - Host=talent-member.peacetrue.cn
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
            - SaveSession
        #子域名静态资源处理
        - id: talent-admin
          uri: ${MICROSERVICE_PROTOCOL:http}://peacetrue.cn
          predicates:
            - Host=talent-admin.peacetrue.cn
          filters:
            - PrefixPath=/talent-admin
        - id: talent-member
          uri: ${MICROSERVICE_PROTOCOL:http}://peacetrue.cn
          predicates:
            - Host=talent-member.peacetrue.cn
          filters:
            - PrefixPath=/talent-member


        #biog
        - id: biog_front
          uri: http://localhost:3000/
          predicates:
            - Path=/,/*.js,/*.json,/static/**,/_next/**,/room/**,/play/**
        - id: biog_back
          uri: http://localhost:8001/
          predicates:
            - Path=/games/**,/socket.io/**

peacetrue:
  static-resources:
    '[/summarize/**]': file:/root/peacetrue/document-antora/public/
    '[/download/**]': file:/root/peacetrue/download/
    '[/talent-admin/**]': file:/root/peacetrue/peacetrue-talent-page/peacetrue-talent-admin-page/build/
    '[/talent-member/**]': file:/root/peacetrue/peacetrue-talent-page/peacetrue-talent-member-page/public/
    '[/MP_verify_t4rKSxor2Mowtjo?.txt]': file:/usr/share/nginx/html/MP_verify_t4rKSxor2MowtjoC.txt

---
spring.profiles: https

server.port: 443

---
spring.profiles: prod

#logging.level.org.springframework: trace
logging.level.com.github.peacetrue: trace
