server.port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/message/**
        - id: test
          uri: https://www.baidu.com/
          predicates:
            - Path=/baidu/**
          filters:
            - RewritePath=/baidu,/

---
spring.profiles: https

server.port: 443
