server.port: 80

spring:
  cloud:
    gateway:
      routes:
        #配置中心监听
        - id: config_center_monitor
          #配置中心地址
          uri: ${MICROSERVICE_PROTOCOL:http}://${MICROSERVICE_CONFIG_HOST:localhost}:${MICROSERVICE_CONFIG_PORT:8888}/
          predicates:
            - Path=/monitor/**
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/message/**
        - id: test
          uri: https://www.baidu.com/
          predicates:
            - Path=/baidu/**
          filters:
            - RewritePath=/baidu,/
        - id: test2
          uri: https://www.baidu.com/
          predicates:
            - Path=/baidu2/**
          filters:
            - RewritePath=/baidu2,/

---
spring.profiles: https

server.port: 443
