server.port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/message/**
        #添加 Github 推送转发
        - id: github_push_forward
          uri: https://localhost/monitor
          predicates:
            #判断请求头：X-GitHub-Event=push
            - Header=X-GitHub-Event,push
        - id: test
          uri: https://www.baidu.com/
          predicates:
            - Path=/baidu/**
          filters:
            - RewritePath=/baidu,/

---
spring.profiles: https

server.port: 443
