server.port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/resource-server/**

---

spring.profiles: https

server.port: 443
