server.port: 80

spring:
  cloud:
    gateway:
      routes:
        #配置中心监听
        - id: config_center_monitor
          #配置中心地址
          uri: ${MICROSERVICE_PROTOCOL:http}://${MICROSERVICE_CONFIG_HOST:localhost}:${MICROSERVICE_CONFIG_PORT:8888}/monitor
          predicates:
            - Path=/monitor
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/message/**
#人才库
peacetrue:
  static-resources:
    '[/peacetrue-talent-admin/**]': file:/root/peacetrue/learn-docker/composes/jenkins/volumes/jenkins-data/workspace/peacetrue-talent/peacetrue-talent-admin-page/build
    '[/peacetrue-talent-member/**]': file:/root/peacetrue/learn-docker/composes/jenkins/volumes/jenkins-data/workspace/peacetrue-talent/peacetrue-talent-member-page/public
---
spring.profiles: https

server.port: 443
