server.port: 80

spring:
  cloud:
    gateway:
      routes:
        #配置中心监听
        - id: config_center_monitor
          #配置中心地址
          uri: ${MICROSERVICE_PROTOCOL:http}://${MICROSERVICE_CONFIG_HOST:localhost}:${MICROSERVICE_CONFIG_PORT:8888}/monitor
          predicates:
            - Path=/monitor
        - id: peacetrue-microservice-resource-server
          uri: lb://peacetrue-microservice-resource-server
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/?(?<segment>.*), /$\{segment}
        - id: peacetrue-microservice-client-inner
          uri: lb://peacetrue-microservice-client-inner
          predicates:
            - Path=/client/**
          filters:
            - RewritePath=/client/?(?<segment>.*), /$\{segment}
#        - id: peacetrue-microservice-authorization-server
#          uri: lb://peacetrue-microservice-authorization-server
#          predicates:
#            - Path=/authorization/**
#          filters:
#            - RewritePath=/authorization/?(?<segment>.*), /$\{segment}

---
spring.config.activate.on-profile: https

server.port: 443
